src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Address_Overriden__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Tracks whether the address has been manually overridden.</description>
        <label>Address Overriden</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Seasonal_Address__c.object
<CustomObject>
    <description>Object for storing a contact&apos;s addresses with start and end dates.</description>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Seasonal Addresses</relationshipLabel>
        <relationshipName>Seasonal_Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Current Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Day__c</fullName>
        <label>End Day</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>End_Month__c</fullName>
        <label>End Month</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Months</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Invalid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Invalid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Day__c</fullName>
        <label>Start Day</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Month__c</fullName>
        <label>Start Month</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Months</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Seasonal Address</label>
    <nameField>
        <displayFormat>SA-{00000}</displayFormat>
        <label>Seasonal Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seasonal Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Months.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>January</fullName>
    </customValue>
    <customValue>
        <fullName>February</fullName>
    </customValue>
    <customValue>
        <fullName>March</fullName>
    </customValue>
    <customValue>
        <fullName>April</fullName>
    </customValue>
    <customValue>
        <fullName>May</fullName>
    </customValue>
    <customValue>
        <fullName>June</fullName>
    </customValue>
    <customValue>
        <fullName>July</fullName>
    </customValue>
    <customValue>
        <fullName>August</fullName>
    </customValue>
    <customValue>
        <fullName>September</fullName>
    </customValue>
    <customValue>
        <fullName>October</fullName>
    </customValue>
    <customValue>
        <fullName>November</fullName>
    </customValue>
    <customValue>
        <fullName>December</fullName>
    </customValue>
    <description>Month names</description>
    <masterLabel>Months</masterLabel>
</GlobalValueSet>

src/classes/SeasonalAddressServiceTest.cls
/**
 * Created by jschultz on 6/6/17.
 */

@IsTest
private class SeasonalAddressServiceTest {
	
	static Contact testContact1;
	static List<Seasonal_Address__c> testAddresses;
	
	static {
		testContact1 = new Contact(
			LastName = 'contact1'
		);
		insert testContact1;
		
		testAddresses = new List<Seasonal_Address__c>{
			new Seasonal_Address__c(
				Contact__c = testContact1.Id
				, Start_Day__c = 1
				, Start_Month__c = 'June'
				, End_Day__c = 1
				, End_Month__c = 'August'
				, Current_Address__c = false
				, Invalid__c = false
				, Street__c = '1street'
				, City__c = '1town'
				, State__c = '1NJ'
				, Country__c = '1USA'
				, Postal_Code__c = '11111'
			),
			new Seasonal_Address__c(
				Contact__c = testContact1.Id
				, Start_Day__c = 1
				, Start_Month__c = 'September'
				, End_Day__c = 1
				, End_Month__c = 'October'
				, Current_Address__c = false
				, Invalid__c = false
				, Street__c = '2street'
				, City__c = '2town'
				, State__c = '2NJ'
				, Country__c = '2USA'
				, Postal_Code__c = '22222'
			)
		};
		
	}
	
	static testMethod void testTrigger() {
		Contact con = [SELECT MailingStreet, MailingCity, MailingState, MailingPostalCode, MailingCountry FROM Contact WHERE Id = :testContact1.Id];
		System.assertEquals(null, con.MailingStreet);
		System.assertEquals(null, con.MailingCity);
		System.assertEquals(null, con.MailingState);
		System.assertEquals(null, con.MailingPostalCode);
		System.assertEquals(null, con.MailingCountry);
		
		Test.startTest();
		
		insert testAddresses;
		
		con = [SELECT MailingStreet, MailingCity, MailingState, MailingPostalCode, MailingCountry FROM Contact WHERE Id = :testContact1.Id];
		System.assertEquals(testAddresses[0].Street__c, con.MailingStreet);
		System.assertEquals(testAddresses[0].City__c, con.MailingCity);
		System.assertEquals(testAddresses[0].State__c, con.MailingState);
		System.assertEquals(testAddresses[0].Postal_Code__c, con.MailingPostalCode);
		System.assertEquals(testAddresses[0].Country__c, con.MailingCountry);
		
		Test.stopTest();
	}
	
	static testMethod void testOverlappingDates() {
		Test.startTest();
		
		insert testAddresses;
		
		Seasonal_Address__c overlap = new Seasonal_Address__c(
			Contact__c = testContact1.Id
			, Start_Day__c = 1
			, Start_Month__c = 'April'
			, End_Day__c = 1
			, End_Month__c = 'August'
			, Current_Address__c = false
			, Invalid__c = false
			, Street__c = '3street'
			, City__c = '3town'
			, State__c = '3NJ'
			, Country__c = '3USA'
			, Postal_Code__c = '33333'
		);
		
		try {
			insert overlap;
			
			System.assert(false, 'None shall pass'); // shouldn't get this far due to exception being thrown.
		}
		catch (Exception e) {}
		
		Test.stopTest();
	}
	
	static testMethod void testInvalidation() {
		Test.startTest();
		
		insert testAddresses;
		
		Contact con = [SELECT MailingStreet, MailingCity, MailingState, MailingPostalCode, MailingCountry FROM Contact WHERE Id = :testContact1.Id];
		System.assertEquals(testAddresses[0].Street__c, con.MailingStreet);
		System.assertEquals(testAddresses[0].City__c, con.MailingCity);
		System.assertEquals(testAddresses[0].State__c, con.MailingState);
		System.assertEquals(testAddresses[0].Postal_Code__c, con.MailingPostalCode);
		System.assertEquals(testAddresses[0].Country__c, con.MailingCountry);
		
		Seasonal_Address__c s = [SELECT Id, Invalid__c, Current_Address__c FROM Seasonal_Address__c WHERE Id = :testAddresses[0].Id];
		System.assertEquals(true, s.Current_Address__c);
		System.assertEquals(false, s.Invalid__c);
		
		s.Invalid__c = true;
		update s;
		
		con = [SELECT MailingStreet, MailingCity, MailingState, MailingPostalCode, MailingCountry FROM Contact WHERE Id = :testContact1.Id];
		System.assertEquals(null, con.MailingStreet);
		System.assertEquals(null, con.MailingCity);
		System.assertEquals(null, con.MailingState);
		System.assertEquals(null, con.MailingPostalCode);
		System.assertEquals(null, con.MailingCountry);
		
		s = [SELECT Current_Address__c FROM Seasonal_Address__c WHERE Id = :testAddresses[0].Id];
		System.assertEquals(false, s.Current_Address__c);
		
		Test.stopTest();
	}
	
	static testMethod void testReverseDates() {
		Seasonal_Address__c sa = new Seasonal_Address__c(
			Contact__c = testContact1.Id
			, Start_Day__c = 1
			, Start_Month__c = 'June'
			, End_Day__c = 1
			, End_Month__c = 'January'
			, Current_Address__c = false
			, Invalid__c = false
			, Street__c = '1street'
			, City__c = '1town'
			, State__c = '1NJ'
			, Country__c = '1USA'
			, Postal_Code__c = '11111'
		);
		
		Test.startTest();
		
		insert sa;
		
		Contact con = [SELECT MailingStreet, MailingCity, MailingState, MailingPostalCode, MailingCountry FROM Contact WHERE Id = :testContact1.Id];
		System.assertEquals(sa.Street__c, con.MailingStreet);
		System.assertEquals(sa.City__c, con.MailingCity);
		System.assertEquals(sa.State__c, con.MailingState);
		System.assertEquals(sa.Postal_Code__c, con.MailingPostalCode);
		System.assertEquals(sa.Country__c, con.MailingCountry);
		
		Test.stopTest();
	}
	
	static testMethod void testControllerMethods() {
		Test.startTest();
		
		insert testAddresses;
		
		List<Seasonal_Address__c> retrievedAddresses = OverrideAddressController.getAddresses(testContact1.Id);
		System.assertEquals(2, retrievedAddresses.size());
		
		Contact con = [SELECT MailingStreet, MailingCity, MailingState, MailingPostalCode, MailingCountry, Address_Overriden__c FROM Contact WHERE Id = :testContact1.Id];
		System.assertEquals(testAddresses[0].Street__c, con.MailingStreet);
		System.assertEquals(testAddresses[0].City__c, con.MailingCity);
		System.assertEquals(testAddresses[0].State__c, con.MailingState);
		System.assertEquals(testAddresses[0].Postal_Code__c, con.MailingPostalCode);
		System.assertEquals(testAddresses[0].Country__c, con.MailingCountry);
		System.assertEquals(false, con.Address_Overriden__c);
		
		OverrideAddressController.overrideAddress(testAddresses[1].Id);
		con = [SELECT MailingStreet, MailingCity, MailingState, MailingPostalCode, MailingCountry, Address_Overriden__c FROM Contact WHERE Id = :testContact1.Id];
		System.assertEquals(testAddresses[1].Street__c, con.MailingStreet);
		System.assertEquals(testAddresses[1].City__c, con.MailingCity);
		System.assertEquals(testAddresses[1].State__c, con.MailingState);
		System.assertEquals(testAddresses[1].Postal_Code__c, con.MailingPostalCode);
		System.assertEquals(testAddresses[1].Country__c, con.MailingCountry);
		System.assertEquals(true, con.Address_Overriden__c);
		
		OverrideAddressController.disableOverride(testContact1.Id);
		con = [SELECT Address_Overriden__c FROM Contact WHERE Id = :testContact1.Id];
		System.assertEquals(false, con.Address_Overriden__c);
		
		Test.stopTest();
	}
}