src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Address_Overriden__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Tracks whether the address has been manually overridden.</description>
        <label>Address Overriden</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Seasonal_Address__c.object
<CustomObject>
    <description>Object for storing a contact&apos;s addresses with start and end dates.</description>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Seasonal Addresses</relationshipLabel>
        <relationshipName>Seasonal_Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Current Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Before_Start__c</fullName>
        <defaultValue>false</defaultValue>
        <label>End Before Start</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Day__c</fullName>
        <label>End Day</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>End_Month_Number__c</fullName>
        <label>End Month Number</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>End_Month__c</fullName>
        <label>End Month</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Months</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Invalid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Invalid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Day__c</fullName>
        <label>Start Day</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Month_Number__c</fullName>
        <label>Start Month Number</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Month__c</fullName>
        <label>Start Month</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Months</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Seasonal Address</label>
    <nameField>
        <displayFormat>SA-{00000}</displayFormat>
        <label>Seasonal Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seasonal Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Months.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>January</fullName>
    </customValue>
    <customValue>
        <fullName>February</fullName>
    </customValue>
    <customValue>
        <fullName>March</fullName>
    </customValue>
    <customValue>
        <fullName>April</fullName>
    </customValue>
    <customValue>
        <fullName>May</fullName>
    </customValue>
    <customValue>
        <fullName>June</fullName>
    </customValue>
    <customValue>
        <fullName>July</fullName>
    </customValue>
    <customValue>
        <fullName>August</fullName>
    </customValue>
    <customValue>
        <fullName>September</fullName>
    </customValue>
    <customValue>
        <fullName>October</fullName>
    </customValue>
    <customValue>
        <fullName>November</fullName>
    </customValue>
    <customValue>
        <fullName>December</fullName>
    </customValue>
    <description>Month names</description>
    <masterLabel>Months</masterLabel>
</GlobalValueSet>

src/classes/DailyAddressUpdaterBatch.cls
/**
* @author: John Schultz
* @date: 2017-06-05
* @description: Batch for updating contact's address to match in-season address.
* @log:
* ----------------------------------------------------------------------------
* Developer       Date          Description
* ----------------------------------------------------------------------------
* John Schultz    2017-06-05    Newly created
*/
global class DailyAddressUpdaterBatch implements Database.Batchable<SObject> {
	
	global Database.QueryLocator start(Database.BatchableContext bc) {
		Integer day = Date.today().day();
		Integer month = Date.today().month();
		
		String q = '';
		q += 'SELECT Id ';
		q += '  , Street__c ';
		q += '  , City__c ';
		q += '  , State__c ';
		q += '  , Postal_Code__c ';
		q += '  , Country__c ';
		q += '  , Current_Address__c ';
		q += '  , Start_Month__c ';
		q += '  , Start_Month_Number__c ';
		q += '  , Start_Day__c ';
		q += '  , End_Month__c ';
		q += '  , End_Month_Number__c ';
		q += '  , End_Day__c ';
		q += '  , Contact__c ';
		q += '  , End_Before_Start__c ';
		q += ' FROM Seasonal_Address__c ';
		q += ' WHERE Invalid__c = false ';
		q += ' AND Current_Address__c = false ';
		q += ' AND Contact__r.Address_Overriden__c = false ';
		
		q += '  AND ( ';
		// end comes before start. reversed dates that cross new year threshold.
		q += '      ( ';
		q += '          End_Before_Start__c = TRUE ';
		q += '          AND ';
		q += '          ( ';
		q += '              ( ';
		q += '                  Start_Month_Number__c > ' + month;
		q += '                  OR ( ';
		q += '                      Start_Month_Number__c = ' + month;
		q += '                      AND Start_Day__c <= ' + day;
		q += '                  ) ';
		q += '              ) ';
		q += '              AND ';
		q += '              ( ';
		q += '                  End_Month_Number__c > ' + month;
		q += '                  OR ( ';
		q += '                      End_Month_Number__c = ' + month;
		q += '                      AND End_Day__c >= ' + day;
		q += '                  ) ';
		q += '              ) ';
		q += '          ) ';
		q += '      ) ';
		q += '      OR ';
		// start comes before end. normal date order.
		q += '      ( ';
		q += '          End_Before_Start__c = FALSE ';
		q += '          AND ';
		q += '          ( ';
		q += '              ( ';
		q += '                  Start_Month_Number__c < ' + month;
		q += '                  OR ( ';
		q += '                      Start_Month_Number__c = ' + month;
		q += '                      AND Start_Day__c <= ' + day;
		q += '                  ) ';
		q += '              ) ';
		q += '              AND ';
		q += '              ( ';
		q += '                  End_Month_Number__c > ' + month;
		q += '                  OR ( ';
		q += '                      End_Month_Number__c = ' + month;
		q += '                      AND End_Day__c >= ' + day;
		q += '                  ) ';
		q += '              ) ';
		q += '          ) ';
		q += '      ) ';
		q += ' ) ';
		
		
		return Database.getQueryLocator(q);
	}
	
	global void execute(Database.BatchableContext bc, List<Seasonal_Address__c> addresses) {
		// disable trigger since we're updating the addresses manually
		SeasonalAddressService.disableAddressUpdateTrigger = true;

		Map<Id, Contact> contacts = SeasonalAddressService.getRelatedContacts(addresses);

		for (Seasonal_Address__c sa : addresses) {
			Contact con = contacts.get(sa.Contact__c);

			// set address to current address
			sa.Current_Address__c = true;
			SeasonalAddressService.existingAddressesToUpdate.add(sa);

			// call method to update related records
			SeasonalAddressService.updateContactAndOtherAddresses(sa, con);
		}

		// commit changes
		SeasonalAddressService.saveUpdatedContactsAndAddresses();
	}
	
	global void finish(Database.BatchableContext bc) {}
}