src/objects/Seasonal_Address__c.object
<CustomObject>
    <description>Object for storing a contact&apos;s addresses with start and end dates.</description>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Seasonal Addresses</relationshipLabel>
        <relationshipName>Seasonal_Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Current Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Day__c</fullName>
        <label>End Day</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>End_Month_Number__c</fullName>
        <label>End Month Number</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>End_Month__c</fullName>
        <label>End Month</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Months</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Invalid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Invalid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Day__c</fullName>
        <label>Start Day</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Month_Number__c</fullName>
        <label>Start Month Number</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Month__c</fullName>
        <label>Start Month</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Months</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Seasonal Address</label>
    <nameField>
        <displayFormat>SA-{00000}</displayFormat>
        <label>Seasonal Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seasonal Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Months.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>January</fullName>
    </customValue>
    <customValue>
        <fullName>February</fullName>
    </customValue>
    <customValue>
        <fullName>March</fullName>
    </customValue>
    <customValue>
        <fullName>April</fullName>
    </customValue>
    <customValue>
        <fullName>May</fullName>
    </customValue>
    <customValue>
        <fullName>June</fullName>
    </customValue>
    <customValue>
        <fullName>July</fullName>
    </customValue>
    <customValue>
        <fullName>August</fullName>
    </customValue>
    <customValue>
        <fullName>September</fullName>
    </customValue>
    <customValue>
        <fullName>October</fullName>
    </customValue>
    <customValue>
        <fullName>November</fullName>
    </customValue>
    <customValue>
        <fullName>December</fullName>
    </customValue>
    <description>Month names</description>
    <masterLabel>Months</masterLabel>
</GlobalValueSet>

src/classes/DailyAddressUpdaterBatchTest.cls
/**
 * Created by jschultz on 6/6/17.
 */

@IsTest
private class DailyAddressUpdaterBatchTest {
	static Contact testContact1;
	static Seasonal_Address__c testAddress;
	
	static {
		testContact1 = new Contact(
			LastName = 'contact1'
		);
		insert testContact1;
		
		testAddress = new Seasonal_Address__c(
			Contact__c = testContact1.Id
			, Start_Day__c = 1
			, Start_Month__c = 'June'
			, Start_Month_Number__c = 6
			, End_Day__c = 1
			, End_Month__c = 'August'
			, End_Month_Number__c = 8
			, Current_Address__c = false
			, Invalid__c = false
			, Street__c = '1street'
			, City__c = '1town'
			, State__c = '1NJ'
			, Country__c = '1USA'
			, Postal_Code__c = '11111'
			);
		
		SeasonalAddressService.disableAddressUpdateTrigger = true;
		
		insert testAddress;
		
	}
	
	static testMethod void testBatch() {
		Test.startTest();
		
		DailyAddressUpdaterBatch batch = new DailyAddressUpdaterBatch();
		Database.executeBatch(batch);
		
		Test.stopTest();
		
		Contact con = [SELECT MailingStreet, MailingCity, MailingState, MailingPostalCode, MailingCountry FROM Contact WHERE Id = :testContact1.Id];
		System.assertEquals(testAddress.Street__c, con.MailingStreet);
		System.assertEquals(testAddress.City__c, con.MailingCity);
		System.assertEquals(testAddress.State__c, con.MailingState);
		System.assertEquals(testAddress.Postal_Code__c, con.MailingPostalCode);
		System.assertEquals(testAddress.Country__c, con.MailingCountry);
	}
}